// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineExaminationSystem;

#nullable disable

namespace OnlineExaminationSystem.Migrations
{
    [DbContext(typeof(OnlineExaminationSystemContext))]
    [Migration("20260129124656_test2")]
    partial class test2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseTrack", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "TrackId")
                        .HasName("PK__CourseTr__DE8A3E2921FD7B46");

                    b.HasIndex("TrackId");

                    b.ToTable("CourseTrack", (string)null);
                });

            modelBuilder.Entity("OnlineExaminationSystem.Attempt", b =>
                {
                    b.Property<int>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttemptId"));

                    b.Property<int>("AttemptNo")
                        .HasColumnType("int");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("InProgress");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AttemptId");

                    b.HasIndex(new[] { "ExamId" }, "IX_Attempts_ExamId");

                    b.HasIndex(new[] { "StudentId" }, "IX_Attempts_StudentId");

                    b.HasIndex(new[] { "ExamId", "StudentId", "AttemptNo" }, "UQ_Attempts_Exam_Student_Attempt")
                        .IsUnique();

                    b.ToTable("Attempts");
                });

            modelBuilder.Entity("OnlineExaminationSystem.AttemptAnswer", b =>
                {
                    b.Property<int>("AttemptAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttemptAnswerId"));

                    b.Property<int>("AttemptId")
                        .HasColumnType("int");

                    b.Property<decimal?>("EarnedMarks")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("SelectedChoiceId")
                        .HasColumnType("int");

                    b.HasKey("AttemptAnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectedChoiceId");

                    b.HasIndex(new[] { "AttemptId" }, "IX_AttemptAnswers_AttemptId");

                    b.HasIndex(new[] { "AttemptId", "QuestionId" }, "UQ_AttemptAnswers_Attempt_Question")
                        .IsUnique();

                    b.ToTable("AttemptAnswers");
                });

            modelBuilder.Entity("OnlineExaminationSystem.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BranchId");

                    b.HasIndex(new[] { "BranchName" }, "UQ_Branches_BranchName")
                        .IsUnique();

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("OnlineExaminationSystem.Choice", b =>
                {
                    b.Property<int>("ChoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChoiceId"));

                    b.Property<string>("ChoiceText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("ChoiceId");

                    b.HasIndex(new[] { "QuestionId" }, "IX_Choices_QuestionId");

                    b.ToTable("Choices", t =>
                        {
                            t.HasTrigger("trg_Choices_ValidateCounts");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("OnlineExaminationSystem.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("CourseId")
                        .HasName("PK_Courses_1");

                    b.HasIndex(new[] { "CourseCode" }, "UQ_Courses_Code")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("OnlineExaminationSystem.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("CreatedByInstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PassingScore")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TotalMarks")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ExamId");

                    b.HasIndex(new[] { "CourseId" }, "IX_Exams_CourseId");

                    b.HasIndex(new[] { "CreatedByInstructorId" }, "IX_Exams_InstructorId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("OnlineExaminationSystem.ExamQuestion", b =>
                {
                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("PointsOverride")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ExamId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex(new[] { "ExamId" }, "IX_ExamQuestions_ExamId");

                    b.HasIndex(new[] { "ExamId", "OrderNo" }, "UQ_ExamQuestions_Order")
                        .IsUnique();

                    b.ToTable("ExamQuestions");
                });

            modelBuilder.Entity("OnlineExaminationSystem.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.HasKey("InstructorId");

                    b.HasIndex("BranchId");

                    b.ToTable("Instructors", t =>
                        {
                            t.HasTrigger("trg_Instructors_RoleCheck");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("OnlineExaminationSystem.InstructorTrack", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.HasKey("InstructorId", "TrackId")
                        .HasName("PK__Instruct__8AA645156963B806");

                    b.HasIndex("TrackId");

                    b.ToTable("InstructorTrack", (string)null);
                });

            modelBuilder.Entity("OnlineExaminationSystem.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("CreatedByInstructorId")
                        .HasColumnType("int");

                    b.Property<decimal>("DefaultMark")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(1m);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("QuestionId");

                    b.HasIndex("CreatedByInstructorId");

                    b.HasIndex(new[] { "CourseId" }, "IX_Questions_CourseId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("OnlineExaminationSystem.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RoleId");

                    b.HasIndex(new[] { "RoleName" }, "UQ_Roles_RoleName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("OnlineExaminationSystem.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("BranchId");

                    b.ToTable("Students", t =>
                        {
                            t.HasTrigger("trg_Students_RoleCheck");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("OnlineExaminationSystem.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopicId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TopicId")
                        .HasName("PK__Topics__022E0F5DACA170FF");

                    b.HasIndex(new[] { "CourseId", "TopicName" }, "UQ_Topics_Course_TopicName")
                        .IsUnique();

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("OnlineExaminationSystem.Track", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("TrackId")
                        .HasName("PK_Tracks_1");

                    b.HasIndex(new[] { "TrackName" }, "UQ_TrackName")
                        .IsUnique();

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("OnlineExaminationSystem.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("CreatedByAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("CreatedByAdminId");

                    b.HasIndex(new[] { "RoleId" }, "IX_Users_RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasTrigger("trg_Users_AdminCreatesInstructorOnly");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("TrackBranch", b =>
                {
                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.HasKey("TrackId", "BranchId")
                        .HasName("PK__TrackBra__30627A1CE264D9DC");

                    b.HasIndex("BranchId");

                    b.ToTable("TrackBranch", (string)null);
                });

            modelBuilder.Entity("CourseTrack", b =>
                {
                    b.HasOne("OnlineExaminationSystem.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__CourseTra__Cours__6442E2C9");

                    b.HasOne("OnlineExaminationSystem.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("FK__CourseTra__Track__65370702");
                });

            modelBuilder.Entity("OnlineExaminationSystem.Attempt", b =>
                {
                    b.HasOne("OnlineExaminationSystem.Exam", "Exam")
                        .WithMany("Attempts")
                        .HasForeignKey("ExamId")
                        .IsRequired()
                        .HasConstraintName("FK_Attempts_Exams");

                    b.HasOne("OnlineExaminationSystem.Student", "Student")
                        .WithMany("Attempts")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Attempts_Students");

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OnlineExaminationSystem.AttemptAnswer", b =>
                {
                    b.HasOne("OnlineExaminationSystem.Attempt", "Attempt")
                        .WithMany("AttemptAnswers")
                        .HasForeignKey("AttemptId")
                        .IsRequired()
                        .HasConstraintName("FK_AttemptAnswers_Attempts");

                    b.HasOne("OnlineExaminationSystem.Question", "Question")
                        .WithMany("AttemptAnswers")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_AttemptAnswers_Questions");

                    b.HasOne("OnlineExaminationSystem.Choice", "SelectedChoice")
                        .WithMany("AttemptAnswers")
                        .HasForeignKey("SelectedChoiceId")
                        .HasConstraintName("FK_AttemptAnswers_Choices");

                    b.Navigation("Attempt");

                    b.Navigation("Question");

                    b.Navigation("SelectedChoice");
                });

            modelBuilder.Entity("OnlineExaminationSystem.Choice", b =>
                {
                    b.HasOne("OnlineExaminationSystem.Question", "Question")
                        .WithMany("Choices")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_Choices_Questions");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("OnlineExaminationSystem.Exam", b =>
                {
                    b.HasOne("OnlineExaminationSystem.Instructor", "CreatedByInstructor")
                        .WithMany("Exams")
                        .HasForeignKey("CreatedByInstructorId")
                        .IsRequired()
                        .HasConstraintName("FK_Exams_Instructors");

                    b.Navigation("CreatedByInstructor");
                });

            modelBuilder.Entity("OnlineExaminationSystem.ExamQuestion", b =>
                {
                    b.HasOne("OnlineExaminationSystem.Exam", "Exam")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamId")
                        .IsRequired()
                        .HasConstraintName("FK_ExamQuestions_Exams");

                    b.HasOne("OnlineExaminationSystem.Question", "Question")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_ExamQuestions_Questions");

                    b.Navigation("Exam");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("OnlineExaminationSystem.Instructor", b =>
                {
                    b.HasOne("OnlineExaminationSystem.Branch", "Branch")
                        .WithMany("Instructors")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_Instructors_Branches");

                    b.HasOne("OnlineExaminationSystem.User", "InstructorNavigation")
                        .WithOne("Instructor")
                        .HasForeignKey("OnlineExaminationSystem.Instructor", "InstructorId")
                        .IsRequired()
                        .HasConstraintName("FK_Instructors_Users");

                    b.Navigation("Branch");

                    b.Navigation("InstructorNavigation");
                });

            modelBuilder.Entity("OnlineExaminationSystem.InstructorTrack", b =>
                {
                    b.HasOne("OnlineExaminationSystem.Track", "Track")
                        .WithMany("InstructorTracks")
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("FK__Instructo__Track__70A8B9AE");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("OnlineExaminationSystem.Question", b =>
                {
                    b.HasOne("OnlineExaminationSystem.Instructor", "CreatedByInstructor")
                        .WithMany("Questions")
                        .HasForeignKey("CreatedByInstructorId")
                        .IsRequired()
                        .HasConstraintName("FK_Questions_Instructors");

                    b.Navigation("CreatedByInstructor");
                });

            modelBuilder.Entity("OnlineExaminationSystem.Student", b =>
                {
                    b.HasOne("OnlineExaminationSystem.Branch", "Branch")
                        .WithMany("Students")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_Students_Branches");

                    b.HasOne("OnlineExaminationSystem.User", "StudentNavigation")
                        .WithOne("Student")
                        .HasForeignKey("OnlineExaminationSystem.Student", "StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Students_Users");

                    b.Navigation("Branch");

                    b.Navigation("StudentNavigation");
                });

            modelBuilder.Entity("OnlineExaminationSystem.Topic", b =>
                {
                    b.HasOne("OnlineExaminationSystem.Course", "Course")
                        .WithMany("Topics")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_Topics_Courses");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("OnlineExaminationSystem.User", b =>
                {
                    b.HasOne("OnlineExaminationSystem.User", "CreatedByAdmin")
                        .WithMany("InverseCreatedByAdmin")
                        .HasForeignKey("CreatedByAdminId")
                        .HasConstraintName("Fk_Users_CreatedByAdmin");

                    b.HasOne("OnlineExaminationSystem.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("CreatedByAdmin");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TrackBranch", b =>
                {
                    b.HasOne("OnlineExaminationSystem.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK__TrackBran__Branc__6166761E");

                    b.HasOne("OnlineExaminationSystem.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("FK__TrackBran__Track__607251E5");
                });

            modelBuilder.Entity("OnlineExaminationSystem.Attempt", b =>
                {
                    b.Navigation("AttemptAnswers");
                });

            modelBuilder.Entity("OnlineExaminationSystem.Branch", b =>
                {
                    b.Navigation("Instructors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("OnlineExaminationSystem.Choice", b =>
                {
                    b.Navigation("AttemptAnswers");
                });

            modelBuilder.Entity("OnlineExaminationSystem.Course", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("OnlineExaminationSystem.Exam", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("ExamQuestions");
                });

            modelBuilder.Entity("OnlineExaminationSystem.Instructor", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("OnlineExaminationSystem.Question", b =>
                {
                    b.Navigation("AttemptAnswers");

                    b.Navigation("Choices");

                    b.Navigation("ExamQuestions");
                });

            modelBuilder.Entity("OnlineExaminationSystem.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("OnlineExaminationSystem.Student", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("OnlineExaminationSystem.Track", b =>
                {
                    b.Navigation("InstructorTracks");
                });

            modelBuilder.Entity("OnlineExaminationSystem.User", b =>
                {
                    b.Navigation("Instructor");

                    b.Navigation("InverseCreatedByAdmin");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
